name: CI
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  code-validation:
    uses: ZooRoyal/reusable-workflows/.github/workflows/code-validation.yml@master
    secrets: inherit
    name: CI
